# Generated by Django 5.2 on 2025-04-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperAdmin",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("admin_super_user", models.CharField(max_length=150, unique=True)),
                ("admin_super_password", models.CharField(max_length=128)),
                ("user_limit", models.PositiveIntegerField()),
                ("user_count", models.PositiveIntegerField(default=0)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Super Admin",
                "verbose_name_plural": "Super Admins",
                "db_table": "super_admin",
            },
        ),
    ]
