# Generated by Django 5.2 on 2025-05-03 21:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_superadmin_super_admin_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channels',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
