# Generated by Django 5.2 on 2025-05-03 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_user_channels_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
