# Generated by Django 5.2 on 2025-05-03 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0006_alter_channel_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='channel',
            table='channels',
        ),
    ]
