# Generated by Django 5.2 on 2025-05-03 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0007_alter_channel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='channel',
            table='console_channel',
        ),
    ]
