# Generated by Django 5.2 on 2025-05-03 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0008_alter_channel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={},
        ),
    ]
