# Generated by Django 5.2 on 2025-05-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0009_alter_channel_options'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE OR REPLACE VIEW channels AS SELECT * FROM console_channel;",
            "DROP VIEW IF EXISTS channels;"
        ),
    ]
