# Generated by Django 5.2 on 2025-05-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0010_add_channels_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="uid",
            field=models.CharField(
                editable=False, max_length=50, null=True, unique=True
            ),
        ),
        migrations.AlterModelTable(
            name="channel",
            table=None,
        ),
    ]
